name: Test Runner Availability

on:
  push:
    branches:
      - main-server-sync

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test runner
        run: |
          echo "Runner is working!"
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"